package com.oceaniq.impact.entity;

import com.oceaniq.impact.enums.*;
import com.oceaniq.user.entity.User;
import com.oceaniq.region.entity.Region;
import jakarta.persistence.*;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

/**
 * Entity representing an environmental impact report
 * used to store info about various reports (EIA, REMP, APEI) uploaded by users
 * 
 * 
 */
@Entity
@Table(name = "impact_reports")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class ImpactReport {

    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // title of report (max length 200 chars / cannot be null)
    @Column(nullable = false, length = 200)
    private String title;

    // type of report determined by ReportType enum
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportType reportType;

    // Impact level (severity) of report
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ImpactLevel impact;

    /**
     * User who uploaded report
     * many-to-one relationship with User entity (many reports --> one user)
     * fetch type LAZY - user data is only loaded from database when needed
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uploaded_by")
    private User uploadedBy;

    /**
     * Region associated with report
     * many-to-one relationship with Region entity (many reports --> one region)
     * fetch type LAZY - region data is only loaded from database when needed
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "region_id")
    private Region region;

    // timestamp when report was created (automatically set by database when
    // created)
    @CreationTimestamp
    private LocalDateTime createdAt;
}
