package com.oceaniq.region.entity;

import com.oceaniq.region.enums.RegionType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Lookup entity representing a geographical location 
 * Used to categorise datasets / incidents / resources based on locations
 */
@Entity
@Table(name = "regions")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Region {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // name of region (must be unique, cannot be null)
    @Column(nullable = false, unique = true, length = 100)
    private String name;
    
    // Description providing details about region (can be null, stored as TEXT for longer content)
    @Column(columnDefinition = "TEXT")
    private String description;
    
    // Geographical coordinates representing region's location (latitude/longitude)
    private String coordinates;
    
    // Name of the ocean the region belongs to
    @Column(length = 100)
    private String oceanName;
    
    // Type of region (Ocean, Sea, Reef, Archipelago)
    @Column(length = 50)
    private RegionType type;

    // Timestamp indicating when region was created, automatically populated when created
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
}