package com.oceaniq.species.entity;

import com.oceaniq.species.enums.*;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Set;

/**
 * Entity representing marine species 
 * Stores marine-related biological, ecological and conservation info
 * used for educational content and datasets
 */
@Entity
@Table(name = "species")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Species {
   
    // Primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // Common name of the species (e.g. Blue Whale)
    @Column(name = "common_name", nullable = false, length = 100)
    private String commonName;
    
    // Scientific (Latin) name of the species (Must be unique)
    @Column(name = "scientific_name", nullable = false, unique = true, length = 100)
    private String scientificName;
    
    // Biological classification category
    @Enumerated(EnumType.STRING)
    @Column(name = "species_category", length = 50)
    private SpeciesCategory speciesCategory;
    
    // Conservation status based on 
    @Enumerated(EnumType.STRING)
    @Column(name = "conservation_status", nullable = false)
    private ConservationStatus conservationStatus;
    
    // Detailed description of species
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    // URL to an image representing species
    @Column(name = "image_url", length = 500)
    private String imageUrl;
    
    // Typical habitat of the species
    @Enumerated(EnumType.STRING)
    @Column(name = "habitat", length = 100)
    private HabitatType habitat; 
    
    // Average size of the species (length, weight etc..)
    @Column(name = "average_size", length = 50)
    private String averageSize;
    
    // Average lifespan of the species.
    @Column(name = "average_lifespan", length = 50)
    private String averageLifespan;
    
    // Dietary classification 
    @Enumerated(EnumType.STRING)
    @Column(name = "diet")
    private DietType diet;
    
    /**
     * Collection of threats impacting species  
     * uses a seperate table to store multiple threat values per species 
     * allows a species to be associated with multiple threats if necceassry
     * stores enum values as readable strings in database 
     * 
     * defines a join table used to store collection of threats: 
     * - species_id: references species entity
     * - threat: stores the enum value
     * defines a set of threat type associated with species (set prevents duplicate entries)
     */
    @ElementCollection(targetClass = ThreatType.class)
    @Enumerated(EnumType.STRING)
    @CollectionTable(
        name = "species_threats", 
        joinColumns = @JoinColumn(name = "species_id"))
    @Column(name = "threat")
    private Set<ThreatType> threats;
    
    // Indicates whether species is featured (highlighted) in platform
    @Column(name = "is_featured", nullable = false)
    private Boolean isFeatured = false;
    
    // Timestamp when species record was created (automatically populated when created)
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    // Timestamp when species record was last updated (automatically updated when modified)
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
   
}