package com.oceaniq.saved.entity;

import com.oceaniq.user.entity.User;
import com.oceaniq.saved.enums.ItemType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity representing an item a user has bookmarked 
 * supports saving different types of items based on the ItemType enum + itemId
 * ensures user cant save the same item more than once
*/
@Entity
@Table(name = "saved_items", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"user_id", "item_type", "item_id"})
})
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class SavedItem {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
    * many-to-one relationship with User entity (many saved items --> one user)
    * fetch type LAZY - user data is only loaded from database when accessed (improves performance when loading datasets without needing uploader data)
    * join column 'user_id' in saved_items table references id in users table (foreign key constraint)
    */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    
    // type of item being saved (stored as string using ItemType enum)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ItemType itemType;
    
    // ID of item being saved
    @Column(nullable = false)
    private Long itemId;
    
    // optional title of the item being saved
    @Column(length = 300)
    private String itemTitle;
    
    // optional description of the item being saved
    @Column(columnDefinition = "TEXT")
    private String itemDescription;

    // optional URL / image of saved item
    private String itemThumbnail;
    
    // timestamp of when item was saved (automatically set when record is created)
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime savedAt;

}