package com.oceaniq.stats.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import org.hibernate.annotations.UpdateTimestamp;
import com.oceaniq.user.entity.User;
import java.time.LocalDateTime;

/**
 * Entity representing user statistics in system (maps to 'user_stats' table in database)
 * contains various fields to track user activity and engagement metrics
 * each user has a one-to-one relationship with this stats entity, linked by user ID
*/
@Entity
@Table(name = "user_stats")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class UserStats {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
     
    // one-to-one relationship with User entity (each user has one stats record)
    // foreign key column 'user_id' references the 'id' column in 'users' table (cannot be null / must be unique)
    @OneToOne
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    
    // various fields to track user activity and engagement metrics (all default to 0 and cannot be null)
    @Column(nullable = false)
    private Integer modulesCompleted = 0;
    
    @Column(nullable = false)
    private Integer datasetsUploaded = 0;
    
    @Column(nullable = false)
    private Integer discussionsStarted = 0;
    
    @Column(nullable = false)
    private Integer incidentsReported = 0;
    
    @Column(nullable = false)
    private Integer totalPoints = 0;
    
    @Column(nullable = false)
    private Integer currentStreak = 0;
    
    @Column(nullable = false)
    private Integer longestStreak = 0;
    
    // date and time of user's last activity (can be null if user has never been active)
    private LocalDateTime lastActivityDate;
    
    // timestamp of when stats record was last updated (automatically updated by Hibernate whenever record is modified)
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}  