package com.oceaniq.module.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import com.oceaniq.module.enums.DifficultyLevel;

/**
 * Entity representing a learning module in the system (maps to 'learning_modules' table in database)
 * groups related lessons together and contains metadata such as title, description, difficulty level, duration
*/
@Entity
@Table(name = "learning_modules")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class LearningModule {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // title of learning module (max length 200 chars / cannot be null)
    @Column(nullable = false, length = 200)
    private String title;
    
    // description of learning module (can be null, stored as TEXT in database for longer content)
    @Column(columnDefinition = "TEXT")
    private String description;
    
    // icon representing module (URL or icon name / max length 50 chars)
    @Column(length = 50)
    private String icon;
    
    // total number of lessons in the module (cannot be null)
    @Column(nullable = false)
    private Integer lessonsCount;
    
    // estimated time to complete module (can be null / stored as string e.g. "2h 30m")
    @Column(length = 50)
    private String duration; 
    
    // category of the module 
    @Column(length = 100)
    private String category;
    
    // difficulty level of module (stored as string using DifficultyLevel enum, defaults to BEGINNER)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DifficultyLevel difficultyLevel = DifficultyLevel.BEGINNER;
    
    /**
     * one-to-many relationship with Lesson entity (one module --> many lessons)
     * mappedBy - "module" indicates that 'module' field in Lesson entity owns the relationship
     * cascade - any changes to LearningModule will cascade to associated lessons (if module is deleted, all its lessons are deleted)
     * orphanRemoval - removes lessons if they are removed from the module's lessons list (prevents orphaned records in database)
     * empty ArrayList is created to store lessons associated with the module (preventing null pointer exceptions when adding lessons to module)
    */
    @OneToMany(mappedBy = "module", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Lesson> lessons = new ArrayList<>();
    
    // timestamp of when module was created (automatically set by database, cannot be null, not updatable)
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    // timestamp of when module was last updated (automatically updated by whenever record is modified)
    @UpdateTimestamp
    private LocalDateTime updatedAt;
    
}
