package com.oceaniq.module.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;
import com.oceaniq.module.enums.LessonType;

/**
 * Entity representing a lesson within a learning module (maps to 'lessons' table in database)
 * each lesson belongs to one learning module
 * contains metadata such as title, content, order within module, duration, type and resource URL
*/
@Entity
@Table(name = "lessons")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Lesson {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * many-to-one relationship with LearningModule entity (many lessons --> one module)
     * fetch type LAZY - module data is only loaded from database when accessed (improves performance when loading lessons without needing module data)
     * join column 'module_id' in lessons table references id in learning_modules table (foreign key constraint)
     * 
    */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "module_id", nullable = false)
    private LearningModule module;
    
    // title of lesson (max length 200 chars / cannot be null)
    @Column(nullable = false, length = 200)
    private String title;
    
    // content of lesson (can be null, stored as TEXT in database for longer content)
    @Column(columnDefinition = "TEXT")
    private String content;
    
    // order of lesson within module (cannot be null)
    @Column(nullable = false)
    private Integer orderIndex;
    
    // estimated time to complete lesson (can be null / stored as string) 
    @Column(length = 50)
    private String duration;
    
    // type of lesson (stored as string using LessonType enum, defaults to READING)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private LessonType type = LessonType.READING;
    
    // Optional external resource (e.g. video URL, document link)
    private String resourceUrl;

}
