package com.oceaniq.module.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import com.oceaniq.user.entity.User;
import com.oceaniq.module.enums.ModuleStatus;

/**
 * Entity representing users progress for each learning module 
 * maps to 'user_module_progress' table in database 
 * each record tracks progress of one user for one module 
*/
@Entity
@Table(name = "user_module_progress", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"user_id", "module_id"})
})
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class UserModuleProgress {
    
    // primary key automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * many-to-one relationship with User entity (many progress records --> one user)
     * fetch type LAZY - user data is only loaded from database when accessed (improves performance when loading progress without needing user data)
     * join column 'user_id' in user_module_progress table references id in users table
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    
    /**
     * many-to-one relationship with LearningModule entity (many progress records --> one module)
     * fetch type LAZY - module data is only loaded from database when accessed (improves performance when loading progress without needing module data)
     * join column 'module_id' in user_module_progress table references id in learning_modules table
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "module_id", nullable = false)
    private LearningModule module;
    
    // progress percentage for the module (0-100) 
    @Column(nullable = false)
    private Integer progress = 0;
    
    // current status of the module for user (stored as string using ModuleStatus enum, defaults to NOT_STARTED)
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ModuleStatus status = ModuleStatus.NOT_STARTED;
    
    // timestamp when user started module 
    private LocalDateTime startedAt;
    
    // timestamp when user completed module 
    private LocalDateTime completedAt;

    // ID of current lesson user is on within modukle
    private Integer currentLesson;
    
    // timestamp of last time user accessed module 
    private LocalDateTime lastAccessedAt;

}