package com.oceaniq.user.entity;

import com.oceaniq.user.enums.UserRole;
import com.oceaniq.user.enums.UserStatus;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Setter;
import lombok.Getter; 
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity representing a user in the system (maps to 'users' table in database)
 * contains authentication, profile and account status info for each user
 * 
*/
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class User {

    // unique identifier automatically generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // user full name (max length 100 chars / cannot be null)
    @Column(nullable = false, length = 100)
    private String name;

    // user email (max length 100 chars / cannot be null / must be unique)
    @Column(nullable = false, unique = true, length = 100)
    private String email;

    // hashed password for authentication (cannot be null)
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /**
     * Role assigned to user (cannot be null, defaults to USER)
     * Value stored as a string in database using UserRole enum
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRole role = UserRole.USER;

    /**
     * Account status for the user (cannot be null, defaults to ACTIVE)
     * Value stored as a string in database using UserStatus enum
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.ACTIVE;

    // Date the user joined (cannot be null)
    @Column(nullable = false)
    private LocalDate joinDate;

    // Timestamp of user's last login (can be null if user has never logged in)
    private LocalDateTime lastLogin;

    // URL to user's avatar image (can be null)
    private String avatarUrl;

    // Timestamp of when user record was created (automatically set by database, cant be null / updatable)
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
  
    // Timestamp of when user record was last updated (automatically set by database, cannot be null)
    @UpdateTimestamp
    private LocalDateTime updatedAt;

}